### ISSUE TITLE
New Line

### ISSUE THREAD

**Issue by rainaster** [j-hc/Reddit_ChatBot_Python#11]
Is it possible to send a message with a new line? I have tried using \n, but it appears that the meesage simply does not send.

**Comment by j-hc** [comment]
you need to escape the control characters or send a raw string like:
`chatbot.send_message(r"new \n line")`
or
`chatbot.send_message("new \\n line")`

I could add a check for this but I think that would cause an unnecessary overhead.

**Comment by rainaster** [comment]
Thank you! This did work for me, but it caused the code to throw these error messages when I used `chatbot.send_message("new \\n line")`

10:26, ERROR: error from callback <bound method WebSockClient.on_message of <Reddit_ChatBot_Python.ws_client.WebSockClient object at 0x0000022061A0D360>>: Invalid control character at: line 1 column 101 (char 100)
10:26, ERROR: Invalid control character at: line 1 column 101 (char 100)

Do you know if there is a way to fix this? Sending the new line still works, but the error messages are cluttering up printing the chat on the console, and seems to be breaking something else in my code. Still trying to figure out why that last bit is happening.

**Comment by rainaster** [comment]
Thank you!

**Comment by j-hc** [comment]
for the future reference: i just pushed the 1.4.9 and it fixes a problem with ws messages which consequently solves new line problem as well. no need for the escaping anymore.

`chatbot.send_message("new \n line")` is fine now
