### ISSUE TITLE
Support for Images

### ISSUE THREAD

**Issue by Rusty-sk** [j-hc/Reddit_ChatBot_Python#13]
Reddit has recently added in the ability to add images to DM's and Group chats. Have you started working on this implementation?

I would rather not re-invent the wheel if you are already addressing this.

**Comment by j-hc** [comment]
chatbot.send_img() exists

**Comment by NGaaad** [comment]
> chatbot.send_img() exists

better documentation is needed

**Comment by j-hc** [comment]
> > chatbot.send_img() exists
> 
> better documentation is needed

i dont have the motivation to write one. though i think the code is pretty readable and self-explanatory. anyone feel free to create a pr with better documentation and i will merge it.
