### ISSUE TITLE
Is there any way to overwrite on_error event?

### ISSUE THREAD

**Issue by arfathyahiya** [j-hc/Reddit_ChatBot_Python#17]
What I wanted to do is
I can see ws client having `on_error` but it just logs the error would be helpful if we can get access to it

```py
        try:
            auth = PasswordAuth(reddit_username=self.username,
                                reddit_password=self.password)
            self.bot = ChatBot(authentication=auth, store_session=False)
        except Exception as e:
            logger.error(f"{Fore.RED}Failed to log in {e} for {a['username']}{Fore.RESET}")
            return

        @self.bot.event.on_error
        def on_error(_):
            print("Some error occured", _)

        @self.bot.event.on_ready
        def on_ready(_):
            logger.info(f"{Fore.GREEN}{self.bot.get_own_name()} ready!{Fore.RESET}")

        self.bot.run_4ever(auto_reconnect=True)
```
EDIT: same goes for `on_close`

**Comment by j-hc** [comment]
which on_error do you mean? the errors from the [websocket](https://github.com/j-hc/Reddit_ChatBot_Python/blob/4eb1cca39a063f628da5c2c786a66084309ff45c/Reddit_ChatBot_Python/_ws_client.py#L131) or [reddit](https://github.com/j-hc/Reddit_ChatBot_Python/blob/4eb1cca39a063f628da5c2c786a66084309ff45c/Reddit_ChatBot_Python/chatbot.py#L34)?
