### ISSUE TITLE
RedditAuthentication.TokenAuth() dosent work

### ISSUE THREAD

**Issue by swedenismycity** [j-hc/Reddit_ChatBot_Python#18]
When i run: 
```
from Reddit_ChatBot_Python import RedditAuthentication
from Reddit_ChatBot_Python import ChatBot

reddit_authentication = RedditAuthentication.TokenAuth(token="REDACTED")

chatbot = ChatBot(print_chat=True,
                  store_session=True,
                  log_websocket_frames=False,
                  authentication=reddit_authentication
                  )

```

It returns: 
```
raceback (most recent call last):
  File "/home/anon/r.py", line 13, in <module>
    chatbot = ChatBot(print_chat=True,
  File "/home/anon/.local/lib/python3.10/site-packages/Reddit_ChatBot_Python/chatbot.py", line 22, in __init__
    sb_access_token, user_id = self._load_session(authentication._get_repr_pkl())
  File "/home/anon/.local/lib/python3.10/site-packages/Reddit_ChatBot_Python/chatbot.py", line 225, in _load_session
    self.__r_authentication.authenticate()
  File "/home/anon/.local/lib/python3.10/site-packages/Reddit_ChatBot_Python/reddit_auth.py", line 23, in authenticate
    self._get_userid_sb_token()
  File "/home/anon/.local/lib/python3.10/site-packages/Reddit_ChatBot_Python/reddit_auth.py", line 32, in _get_userid_sb_token
    self.sb_access_token = sb_token_j['sb_access_token']
KeyError: 'sb_access_token'
```
I know for a fact that the access_token works because i have used it in my own POST requests. And I checked out your code, we are using the same kind of token. Login with Username and Password works so i find that a bit strange. 

It returns the same error when I feed it something wrong as well.

**Comment by j-hc** [comment]
where did you get the token from?

**Comment by j-hc** [comment]
where did you get the token from

**Comment by swedenismycity** [comment]
```
 client_id = 'REDACTED'
    client_secret = 'REDACTED'

    data = { 'grant_type': 'authorization_code', 
        'code': code, 
        'redirect_uri': 'http://localhost:3000/login/callback' 
        }
    headers = {
        'User-agent': 'your bot 0.1 by /u/swedenismycity0403'
        }
    url = 'https://www.reddit.com/api/v1/access_token/'

    r = requests.post(url, data=data, headers=headers, auth=(client_id, client_secret))
    access_token = r.json()['access_token']
```
I know this works because i've used it to make requests like this:
```

    headers = {
        "Authorization": "bearer "+access_token,
        'User-agent': 'yourbot 0.1 by /u/swedenismycity0403'
    }
    response = requests.get("https://oauth.reddit.com/api/v1/me", headers=headers)
    print(response.json()['id']) # returns 'swedensimycity0403'
```

**Comment by j-hc** [comment]
read the first paragraph of the readme
> works either with reddit username & password or the api token (not a regular one you get from your registered app as it's not fully scoped)

the only way to get that token is to use either RedditAuthentication.PasswordAuth or by inspecting the requests done by the browser.

**Comment by swedenismycity** [comment]
I don't get it. 

TokenAuth() is extended by _RedditAuthBase. And when you initialize TokenAuth() you use the token variable to assign api.token. api.token stores the access_token you use with oauth, right?

And since api.token is assigned by the token variable in TokenAuth() they must be the same.

**Comment by j-hc** [comment]
> I don't get it.
> 
> TokenAuth() is extended by _RedditAuthBase. And when you initialize TokenAuth() you use the token variable to assign api.token. api.token stores the access_token you use with oauth, right?
> 
> And since api.token is assigned by the token variable in TokenAuth() they must be the same.

RedditAuthBase imitates the reddit mobile app which is btw against the reddit tos. thats how it obtains the fully scoped token.
