### ISSUE TITLE
How do I initiate a chat?

### ISSUE THREAD

**Issue by jt0dd** [j-hc/Reddit_ChatBot_Python#20]
I see the method for sending a new message but am not extremely experienced with Python yet and am struggling to get a minimal example of just starting a new chat with a particular user working.

**Comment by j-hc** [comment]
this is how to start a dm once the bot is started, doesnt work for you?
https://github.com/j-hc/Reddit_ChatBot_Python/blob/4eb1cca39a063f628da5c2c786a66084309ff45c/examples/casual_chatbot.py#L107-L112

**Comment by jt0dd** [comment]
Yeah it didn’t work. I just automated the browser fully with selenium to do
it API-less instead 😂

**Comment by j-hc** [comment]
it works. the problem is on your end and i cant help you without any logs or something.

**Comment by jt0dd** [comment]
Well that was the thing, there were no error logs or anything, just nothing
happened with that particular event. Quiet failure. And I did get some
messaging to work (only sending to one user, my own alt account), and after
creating a chat manually, but then the account was shadow banned. Could no
longer access the chat feature on that account. Looked it up and it is a
thing that other people have reported as happening.
