### ISSUE TITLE
Any way to bridge reddit group using Matterbridge API?

### ISSUE THREAD

**Issue by SonaliBendre** [j-hc/Reddit_ChatBot_Python#3]
I'm not talking community room but the reddit group

**Comment by scrubjay55** [comment]
afaik this already exists: https://github.com/bonehurtingjuice/mattereddit

It just needs to be updated with the latest minor name changes i made though.

**Comment by scrubjay55** [comment]
afaik this already exists: https://github.com/bonehurtingjuice/mattereddit

It just needs to be updated with the latest changes i made though.

**Comment by SonaliBendre** [comment]
> afaik this already exists: https://github.com/bonehurtingjuice/mattereddit
> 
> It just needs to be updated with the latest changes i made though.

I'm not a coder, so its hard for me to do it, can you ask him?

And can we discuss about reddit chat bridge in dm? tell me where to chat with you, if you don't mind

**Comment by scrubjay55** [comment]
No probs. It's a 5 min task. I will fork a make the changes when I have the time.

I use reddit DMs btw: u/perokisdead

**Comment by scrubjay55** [comment]
No probs. It's a 5 min task. I will fork and make the changes when I have the time.

You can write from reddit DMs btw: u/perokisdead

**Comment by SonaliBendre** [comment]
Thanks a lot sir, btw check your dm on reddit

**Comment by scrubjay55** [comment]
Here it is: https://github.com/scrubjay55/mattereddit

**Comment by SonaliBendre** [comment]
@j-hc `ERROR: error from callback <bound method WebSockClient.on_message of <Reddit_ChatBot_Python._ws_client.WebSockClient object at 0x6e64983bb0>>: 'NoneType' object has no attribute 'get'
 ERROR: 'NoneType' object has no attribute 'get'`


Getting this weird error and reddit messages aren't posted to matterbridge api
