### ISSUE TITLE
Error 400113 (What does this mean, and how do I fix it)?

### ISSUE THREAD

**Issue by RylanSchaeffer** [j-hc/Reddit_ChatBot_Python#9]
The below code is throwing the following error: `Reddit_ChatBot_Python._utils.exceptions.APIException: {"message":"Platform API Error","code":400113,"error":true}`

```
@chatbot.event.on_ready
def report_channels(_):
    channels = chatbot.get_channels()
    for channel in channels:
        # Messages come in reverse chronological order (oldest last)
        messages = chatbot.get_older_messages(channel_url=channel.channel_url,
                                              prev_limit=1000)
```

What does this error mean? How do I fix it?

**Comment by RylanSchaeffer** [comment]
The limit seems to be the issue. When I change the limit from 1000 to 100, the error goes away.

**Comment by j-hc** [comment]
Just like in most other places in the reddit's api (comments, posts), elements that are returned are limited within 100 elements. if you want to get more than 100 messages you will need to make multiple requests. you can have a look at the example in the readme.
